#!/bin/bash

for action in 'create' 'list' 'show' 'update' 'delete';
do
    mkdir -p scenarios/$1_$action
    pushd scenarios/$1_$action;
    touch metadata.py;
    for lang in 'ruby' 'python' 'php' 'curl';
    do
        touch $lang.mako;
    done
    popd;
done
